### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ReazCho** [Michele-Arici/complete_daily_bonus#1]
When you close it or win  sometnig and avtomatic closed your cursur stay on the screen

**Comment by Michele-Arici** [comment]
have you renamed the folder script?

**Comment by ReazCho** [comment]
Yes i did to VinewoodSign

**Comment by Michele-Arici** [comment]
did you also changed the event and post requests names? otherwise it won't find the script

**Comment by ReazCho** [comment]
i dont thing so , how to do it

**Comment by ReazCho** [comment]
I renamed the script to daily_bonus

**Comment by Michele-Arici** [comment]
do a find in both html/app.js and client.lua of "complete_daily_bonus" and add the name of the folder
