### ISSUE TITLE
Script Bug

### ISSUE THREAD

**Issue by FieryPig22YT** [Michele-Arici/complete_daily_bonus#2]
Sometimes the script doesn't activate and opens like this!
![image](https://github.com/Michele-Arici/complete_daily_bonus/assets/111526761/1e14e867-cb21-4c5f-90e5-e0d37379973b)
Also players sometimes don't recieve items

**Comment by Michele-Arici** [comment]
If it opens like that it means the script still not finished to initialize, when you get the notification of initialization you should be able to open it without problems, for the items it depends what items you mean and how you implemented the server file

**Comment by FieryPig22YT** [comment]
> If it opens like that it means the script still not finished to initialize, when you get the notification of initialization you should be able to open it without problems, for the items it depends what items you mean and how you implemented the server file

Okay thanks. For testing reasons, how can i reset the timer?

**Comment by Michele-Arici** [comment]
i will add a function for that

**Comment by FieryPig22YT** [comment]
> If it opens like that it means the script still not finished to initialize, when you get the notification of initialization you should be able to open it without problems, for the items it depends what items you mean and how you implemented the server file

But why does the script work for some players and for others it doesn't, even after it is initialized?

**Comment by Michele-Arici** [comment]
i will release a fix soon
